import Architect
import Mathlib.AlgebraicTopology.SimplicialSet.HomotopyCat

open CategoryTheory SSet

attribute [blueprint
  "prop:free-refl-quiver"
  (statement := /--
  The functor that carries a category to its underlying reflexive quiver has a left adjoint,
  defining the free category on a reflexive quiver:
  \begin{center}
    \begin{tikzcd}[column sep=huge]
      \mathcal{C}at \arrow[r, start anchor=353, end anchor=190, bend right, hook', "U"'] \arrow[r,
      phantom, "\bot"] & r\mathcal{Q}uiv \arrow[l, start anchor=170, end anchor=7, bend right, "F"'
      pos=.48]
    \end{tikzcd}
    \end{center}
  -/)
  (proof := /-- This has been formalized and is now in Mathlib. -/)
  (latexEnv := "proposition")]
  ReflQuiv.adj

attribute [blueprint
  "defn:one-truncation"
  (statement := /--
  By 1-truncating, any simplicial set $X$ has an underlying \textbf{reflexive quiver} or
  \textbf{reflexive directed graph} with the 0-simplices of $X$ defining the objects and the
  1-simplices defining the arrows:
  \begin{center}
  \begin{tikzcd}
  X_1 \arrow[r, shift left=.75em, "\cdot\face^1"] \arrow[r, shift right=.75em, "\cdot\face^0"'] &
  X_0, \arrow[l, "\cdot\degen^0" description]
  \end{tikzcd}
  \end{center}
  By convention, the source of an arrow $f \in X_1$ is its 0th face $f \cdot \face^1$ (the face
  opposite 1) while the target is its 1st face $f \cdot \face^0$ (the face opposite 0).
  -/)]
  oneTruncation₂

attribute [blueprint
  "defn:homotopy-cat"
  (title := /-- {the homotopy category \cite[\S2.4]{GabrielZisman:1967cf}} -/)
  (statement := /--
  The \textbf{free category} on this reflexive directed graph has $X_0$ as its object set,
  degenerate 1-simplices serving as identity morphisms, and nonidentity morphisms defined to be
  finite directed paths of nondegenerate 1-simplices. The \textbf{homotopy category} $\ho{X}$ of $X$
  is the quotient of the free category on its underlying reflexive directed graph by the
  congruence\footnote{A binary relation $\sim$ on parallel arrows of a 1-category is a
  \textbf{congruence} if it is an equivalence relation that is closed under pre- and
  post-composition: if $f \sim g$ then $hfk \sim hgk$.} generated by imposing a composition relation
  $h = g \circ f$ witnessed by 2-simplices
    \begin{center}
    \begin{tikzcd}[row sep=small, column sep=small]
    & x_1 \arrow[dr, "g"] \\ x_0 \arrow[ur, "f"] \arrow[rr, "h"'] & & x_2
    \end{tikzcd}
    \end{center}
  -/)]
  Truncated.HomotopyCategory
