/-
Copyright (c) 2026 Johns Hopkins Category Theory Seminar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johns Hopkins Category Theory Seminar
-/

import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.CoherentIso
import Mathlib.AlgebraicTopology.Quasicategory.Basic

open CategoryTheory Simplicial

namespace SSet

/-- A 1-simplex is an isomorphism if it is invertible as the edge between its endpoints. -/
def IsIsoSimplex {A : SSet} (s : A _⦋1⦌) : Prop :=
  Nonempty (Edge.IsIso (Edge.mk s rfl rfl))

/-- Any invertible edge whose underlying 1-simplex is `s` gives an iso 1-simplex. -/
theorem isIsoSimplex_of_isIso {A : SSet} {x₀ x₁ : A _⦋0⦌} {s : A _⦋1⦌}
    {e : Edge x₀ x₁} (he : e.IsIso) (h : e.edge = s) : IsIsoSimplex s :=
  ⟨he.ofEq h⟩

/-- An invertible edge is an iso 1-simplex. -/
theorem isIsoSimplex_of_edge {A : SSet} {a₀ a₁ : A _⦋0⦌} {e : Edge a₀ a₁}
    (he : e.IsIso) : IsIsoSimplex e.edge :=
  isIsoSimplex_of_isIso he rfl

/-- A degenerate identity edge is an iso 1-simplex. -/
theorem isIsoSimplex_id {A : SSet} (a : A _⦋0⦌) : IsIsoSimplex (Edge.id a).edge :=
  isIsoSimplex_of_isIso (Edge.IsIso.isIsoId a) rfl

/-- Reindexing an iso 1-simplex along an endomorphism of `[1]` gives an iso 1-simplex. -/
theorem isIsoSimplex_map_one_one {A : SSet} {s : A _⦋1⦌} (hs : IsIsoSimplex s)
    (g : (⦋1⦌ : SimplexCategory) ⟶ ⦋1⦌) : IsIsoSimplex (A.map g.op s) := by
  rcases SimplexCategory.eq_of_one_to_one g with ⟨a, rfl⟩ | rfl
  · set v := A.map (SimplexCategory.const ⦋0⦌ ⦋1⦌ a).op s with hv
    have hconst : SimplexCategory.const ⦋1⦌ ⦋0⦌ 0 = SimplexCategory.σ (0 : Fin 1) :=
      (SimplexCategory.eq_const_to_zero _).symm
    have key : (Edge.id v).edge = A.map (SimplexCategory.const ⦋1⦌ ⦋1⦌ a).op s := by
      rw [Edge.id_edge]
      show A.map (SimplexCategory.σ (0 : Fin 1)).op v = _
      rw [← hconst, hv, SimplexCategory.const_fac_thru_zero ⦋1⦌ ⦋1⦌ a,
        op_comp, Functor.map_comp_apply]
    exact isIsoSimplex_of_isIso (Edge.IsIso.isIsoId v) key
  · rw [op_id, Functor.map_id_apply]
    exact hs

/-- The maximal subcomplex whose 1-faces are all invertible edges. -/
def isoCore (A : SSet) : A.Subcomplex where
  obj n := { x | ∀ (f : (⦋1⦌ : SimplexCategory) ⟶ n.unop), IsIsoSimplex (A.map f.op x) }
  map {U V} i := by
    intro x hx f
    have e : A.map f.op (A.map i x) = A.map ((f ≫ i.unop).op) x := by
      rw [← types_comp_apply (A.map i) (A.map f.op), ← A.map_comp]
      rfl
    rw [e]
    exact hx (f ≫ i.unop)

/-- Membership in `isoCore` unfolds to all 1-faces being iso 1-simplices. -/
theorem mem_isoCore_obj_iff {A : SSet} {n : SimplexCategoryᵒᵖ} (x : A.obj n) :
    x ∈ (isoCore A).obj n ↔
      ∀ (f : (⦋1⦌ : SimplexCategory) ⟶ n.unop), IsIsoSimplex (A.map f.op x) :=
  Iff.rfl

/-- A 1-simplex lies in `isoCore` iff it is an iso 1-simplex. -/
theorem mem_isoCore_obj_one_iff {A : SSet} (s : A _⦋1⦌) :
    s ∈ (isoCore A).obj (Opposite.op ⦋1⦌) ↔ IsIsoSimplex s := by
  constructor
  · intro h
    have := h (𝟙 ⦋1⦌)
    rwa [op_id, Functor.map_id_apply] at this
  · intro hs f
    exact isIsoSimplex_map_one_one hs f

/-- Every vertex lies in `isoCore`. -/
theorem mem_isoCore_obj_zero {A : SSet} (a : A _⦋0⦌) :
    a ∈ (isoCore A).obj (Opposite.op ⦋0⦌) := by
  intro f
  have hconst : SimplexCategory.const ⦋1⦌ ⦋0⦌ 0 = SimplexCategory.σ (0 : Fin 1) :=
    (SimplexCategory.eq_const_to_zero _).symm
  have hf : f = SimplexCategory.σ (0 : Fin 1) := by
    rw [SimplexCategory.eq_const_to_zero f, hconst]
  subst hf
  exact isIsoSimplex_of_isIso (Edge.IsIso.isIsoId a) (by rw [Edge.id_edge]; rfl)

/-- The subcomplex generated by an invertible edge sits inside `isoCore`. -/
theorem ofSimplex_edge_le_isoCore {A : SSet} {a₀ a₁ : A _⦋0⦌} {e : Edge a₀ a₁}
    (he : e.IsIso) :
    Subcomplex.ofSimplex e.edge ≤ isoCore A := by
  rw [Subcomplex.ofSimplex_le_iff]
  exact (mem_isoCore_obj_one_iff e.edge).mpr (isIsoSimplex_of_edge he)

/-- The classifying map of an invertible edge factors through `isoCore`. -/
theorem range_edge_le_isoCore {A : SSet} {a₀ a₁ : A _⦋0⦌} {e : Edge a₀ a₁}
    (he : e.IsIso) :
    Subcomplex.range (yonedaEquiv.symm e.edge) ≤ isoCore A := by
  rw [Subcomplex.range_eq_ofSimplex, Equiv.apply_symm_apply]
  exact ofSimplex_edge_le_isoCore he

end SSet
