/-
Copyright (c) 2026 Johns Hopkins Category Theory Seminar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johns Hopkins Category Theory Seminar
-/

import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.CoherentIso
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.StdSimplex
import Mathlib.AlgebraicTopology.Quasicategory.Basic

open CategoryTheory Simplicial Opposite

namespace SSet

/-- A 1-simplex is an isomorphism if it is invertible as the edge between its endpoints. -/
def IsIsoSimplex {A : SSet} (s : A _⦋1⦌) : Prop :=
  Nonempty (Edge.IsIso (Edge.mk s rfl rfl))

/-- Any invertible edge whose underlying 1-simplex is `s` gives an iso 1-simplex. -/
theorem isIsoSimplex_of_isIso {A : SSet} {x₀ x₁ : A _⦋0⦌} {s : A _⦋1⦌}
    {e : Edge x₀ x₁} (he : e.IsIso) (h : e.edge = s) : IsIsoSimplex s :=
  ⟨he.ofEq h⟩

/-- An invertible edge is an iso 1-simplex. -/
theorem isIsoSimplex_of_edge {A : SSet} {a₀ a₁ : A _⦋0⦌} {e : Edge a₀ a₁}
    (he : e.IsIso) : IsIsoSimplex e.edge :=
  isIsoSimplex_of_isIso he rfl

/-- A degenerate identity edge is an iso 1-simplex. -/
theorem isIsoSimplex_id {A : SSet} (a : A _⦋0⦌) : IsIsoSimplex (Edge.id a).edge :=
  isIsoSimplex_of_isIso (Edge.IsIso.isIsoId a) rfl

/-- Reindexing an iso 1-simplex along an endomorphism of `[1]` gives an iso 1-simplex. -/
theorem isIsoSimplex_map_one_one {A : SSet} {s : A _⦋1⦌} (hs : IsIsoSimplex s)
    (g : (⦋1⦌ : SimplexCategory) ⟶ ⦋1⦌) : IsIsoSimplex (A.map g.op s) := by
  rcases SimplexCategory.eq_of_one_to_one g with ⟨a, rfl⟩ | rfl
  · set v := A.map (SimplexCategory.const ⦋0⦌ ⦋1⦌ a).op s with hv
    have hconst : SimplexCategory.const ⦋1⦌ ⦋0⦌ 0 = SimplexCategory.σ (0 : Fin 1) :=
      (SimplexCategory.eq_const_to_zero _).symm
    have key : (Edge.id v).edge = A.map (SimplexCategory.const ⦋1⦌ ⦋1⦌ a).op s := by
      rw [Edge.id_edge]
      show A.map (SimplexCategory.σ (0 : Fin 1)).op v = _
      rw [← hconst, hv, SimplexCategory.const_fac_thru_zero ⦋1⦌ ⦋1⦌ a,
        op_comp, Functor.map_comp_apply]
    exact isIsoSimplex_of_isIso (Edge.IsIso.isIsoId v) key
  · rw [op_id, Functor.map_id_apply]
    exact hs

/-- The maximal subcomplex whose 1-faces are all invertible edges. -/
def isoCore (A : SSet) : A.Subcomplex where
  obj n := { x | ∀ (f : (⦋1⦌ : SimplexCategory) ⟶ n.unop), IsIsoSimplex (A.map f.op x) }
  map {U V} i := by
    intro x hx f
    have e : A.map f.op (A.map i x) = A.map ((f ≫ i.unop).op) x := by
      rw [← types_comp_apply (A.map i) (A.map f.op), ← A.map_comp]
      rfl
    rw [e]
    exact hx (f ≫ i.unop)

/-- Membership in `isoCore` unfolds to all 1-faces being iso 1-simplices. -/
theorem mem_isoCore_obj_iff {A : SSet} {n : SimplexCategoryᵒᵖ} (x : A.obj n) :
    x ∈ (isoCore A).obj n ↔
      ∀ (f : (⦋1⦌ : SimplexCategory) ⟶ n.unop), IsIsoSimplex (A.map f.op x) :=
  Iff.rfl

/-- A 1-simplex lies in `isoCore` iff it is an iso 1-simplex. -/
theorem mem_isoCore_obj_one_iff {A : SSet} (s : A _⦋1⦌) :
    s ∈ (isoCore A).obj (Opposite.op ⦋1⦌) ↔ IsIsoSimplex s := by
  constructor
  · intro h
    have := h (𝟙 ⦋1⦌)
    rwa [op_id, Functor.map_id_apply] at this
  · intro hs f
    exact isIsoSimplex_map_one_one hs f

/-- Every vertex lies in `isoCore`. -/
theorem mem_isoCore_obj_zero {A : SSet} (a : A _⦋0⦌) :
    a ∈ (isoCore A).obj (Opposite.op ⦋0⦌) := by
  intro f
  have hconst : SimplexCategory.const ⦋1⦌ ⦋0⦌ 0 = SimplexCategory.σ (0 : Fin 1) :=
    (SimplexCategory.eq_const_to_zero _).symm
  have hf : f = SimplexCategory.σ (0 : Fin 1) := by
    rw [SimplexCategory.eq_const_to_zero f, hconst]
  subst hf
  exact isIsoSimplex_of_isIso (Edge.IsIso.isIsoId a) (by rw [Edge.id_edge]; rfl)

/-- The subcomplex generated by an invertible edge sits inside `isoCore`. -/
theorem ofSimplex_edge_le_isoCore {A : SSet} {a₀ a₁ : A _⦋0⦌} {e : Edge a₀ a₁}
    (he : e.IsIso) :
    Subcomplex.ofSimplex e.edge ≤ isoCore A := by
  rw [Subcomplex.ofSimplex_le_iff]
  exact (mem_isoCore_obj_one_iff e.edge).mpr (isIsoSimplex_of_edge he)

/-- The classifying map of an invertible edge factors through `isoCore`. -/
theorem range_edge_le_isoCore {A : SSet} {a₀ a₁ : A _⦋0⦌} {e : Edge a₀ a₁}
    (he : e.IsIso) :
    Subcomplex.range (yonedaEquiv.symm e.edge) ≤ isoCore A := by
  rw [Subcomplex.range_eq_ofSimplex, Equiv.apply_symm_apply]
  exact ofSimplex_edge_le_isoCore he

/-- Recover an `Edge.IsIso` from the proposition that the underlying 1-simplex is an iso simplex. -/
theorem Edge.isIso_of_isIsoSimplex {A : SSet} {x₀ x₁ : A _⦋0⦌} (e : Edge x₀ x₁)
    (h : IsIsoSimplex e.edge) : Nonempty e.IsIso := by
  obtain ⟨he⟩ := h
  exact ⟨he.ofEq rfl⟩

/-- Closure for a single `2`-simplex: in a quasicategory, if the outer faces `δ 2` and `δ 0`
of a `2`-simplex are iso 1-simplices, then so is the diagonal face `δ 1`. -/
theorem isIsoSimplex_δ₁_of_outer {A : SSet} [Quasicategory A] (σ : A _⦋2⦌)
    (h₂ : IsIsoSimplex (A.δ 2 σ)) (h₀ : IsIsoSimplex (A.δ 0 σ)) :
    IsIsoSimplex (A.δ 1 σ) := by
  obtain ⟨x₀, x₁, x₂, e₀₁, e₁₂, e₀₂, c, hc⟩ := Edge.CompStruct.exists_of_simplex σ
  subst hc
  rw [c.d₁]
  rw [c.d₂] at h₂
  rw [c.d₀] at h₀
  obtain ⟨hf⟩ := Edge.isIso_of_isIsoSimplex e₀₁ h₂
  obtain ⟨hg⟩ := Edge.isIso_of_isIsoSimplex e₁₂ h₀
  exact isIsoSimplex_of_edge (Edge.IsIso.ofCompStruct c hf hg)

/-- If `g : Δ[n] ⟶ A` extends a horn map `τ : Λ[n, i] ⟶ isoCore A`, then `g`'s
value on any simplex coming from the horn lands in `isoCore A`. -/
theorem app_mem_isoCore_of_mem_horn {A : SSet} {n : ℕ} {i : Fin (n + 1)}
    {τ : (Λ[n, i] : SSet) ⟶ (isoCore A : SSet)} {g : Δ[n] ⟶ A}
    (hg : τ ≫ (isoCore A).ι = Λ[n, i].ι ≫ g)
    {m : SimplexCategoryᵒᵖ} (y : (Λ[n, i] : SSet).obj m) :
    g.app m y.val ∈ (isoCore A).obj m := by
  have key : g.app m y.val = (τ.app m y).val := by
    have hgm : (Λ[n, i].ι ≫ g).app m y = (τ ≫ (isoCore A).ι).app m y := by rw [hg]
    simpa using hgm
  rw [key]
  exact (τ.app m y).property

/-- Inner-horn closure: a filler of an inner horn in `A` whose boundary lands in `isoCore A`
also lands in `isoCore A`. -/
theorem filler_mem_isoCore {A : SSet} [Quasicategory A] {n : ℕ} {i : Fin (n + 1)}
    (h0 : 0 < i) (hn : i < Fin.last n)
    {τ : (Λ[n, i] : SSet) ⟶ (isoCore A : SSet)} {g : Δ[n] ⟶ A}
    (hg : τ ≫ (isoCore A).ι = Λ[n, i].ι ≫ g) :
    yonedaEquiv g ∈ (isoCore A).obj (op ⦋n⦌) := by
  rw [mem_isoCore_obj_iff]
  intro f
  by_cases hmem : stdSimplex.objEquiv.symm f ∈ Λ[n, i].obj (op ⦋1⦌)
  · rw [map_yonedaEquiv]
    exact (mem_isoCore_obj_one_iff _).mp (app_mem_isoCore_of_mem_horn hg ⟨_, hmem⟩)
  · rw [Fin.lt_def, Fin.val_zero] at h0
    rw [Fin.lt_def, Fin.val_last] at hn
    by_cases hn3 : 1 + 1 < n
    · rw [horn_obj_eq_univ i 1 hn3] at hmem
      exact absurd (Set.mem_univ _) hmem
    · have hn2 : n = 2 := by omega
      subst hn2
      have hi1 : i = 1 := by
        apply Fin.ext
        simp only [Fin.val_one]
        omega
      subst hi1
      have hf1 : f = SimplexCategory.δ 1 := by
        rw [mem_horn_iff, not_not, stdSimplex.coe_asOrderHom_objEquiv_symm] at hmem
        have m0 : (0 : Fin 3) ∈ Set.range ⇑(ConcreteCategory.hom f) := by
          have h : (0 : Fin 3) ∈ Set.range ⇑(ConcreteCategory.hom f) ∪ ({1} : Set (Fin 3)) :=
            hmem ▸ Set.mem_univ _
          rcases h with h | h
          · exact h
          · exact absurd h (by decide)
        have m2 : (2 : Fin 3) ∈ Set.range ⇑(ConcreteCategory.hom f) := by
          have h : (2 : Fin 3) ∈ Set.range ⇑(ConcreteCategory.hom f) ∪ ({1} : Set (Fin 3)) :=
            hmem ▸ Set.mem_univ _
          rcases h with h | h
          · exact h
          · exact absurd h (by decide)
        obtain ⟨k0, hk0⟩ := m0
        obtain ⟨k2, hk2⟩ := m2
        have b0 := ((ConcreteCategory.hom f) 0).isLt
        have b1 := ((ConcreteCategory.hom f) 1).isLt
        have hmono : ((ConcreteCategory.hom f) 0).val ≤ ((ConcreteCategory.hom f) 1).val :=
          (ConcreteCategory.hom f).monotone' (show (0 : Fin 2) ≤ 1 by decide)
        have v0 := congrArg Fin.val hk0
        have v2 := congrArg Fin.val hk2
        have hval : ((ConcreteCategory.hom f) 0).val = 0 ∧
            ((ConcreteCategory.hom f) 1).val = 2 := by
          fin_cases k0 <;> fin_cases k2 <;> simp_all
        obtain ⟨hv0, hv2⟩ := hval
        apply SimplexCategory.Hom.ext
        ext k
        fin_cases k
        · show ((ConcreteCategory.hom f) 0).val = _
          rw [hv0]
          decide
        · show ((ConcreteCategory.hom f) 1).val = _
          rw [hv2]
          decide
      subst hf1
      apply isIsoSimplex_δ₁_of_outer
      · show IsIsoSimplex (A.map (SimplexCategory.δ 2).op (yonedaEquiv g))
        rw [map_yonedaEquiv]
        have hm2 : stdSimplex.objEquiv.symm (SimplexCategory.δ (2 : Fin 3))
            ∈ Λ[2, 1].obj (op ⦋1⦌) := by
          rw [objEquiv_symm_δ_mem_horn_iff]
          decide
        exact (mem_isoCore_obj_one_iff _).mp (app_mem_isoCore_of_mem_horn hg ⟨_, hm2⟩)
      · show IsIsoSimplex (A.map (SimplexCategory.δ 0).op (yonedaEquiv g))
        rw [map_yonedaEquiv]
        have hm0 : stdSimplex.objEquiv.symm (SimplexCategory.δ (0 : Fin 3))
            ∈ Λ[2, 1].obj (op ⦋1⦌) := by
          rw [objEquiv_symm_δ_mem_horn_iff]
          decide
        exact (mem_isoCore_obj_one_iff _).mp (app_mem_isoCore_of_mem_horn hg ⟨_, hm0⟩)

end SSet
