import VersoBlueprint

open Informal

tex_prelude r#"
\newcommand{\ec}[1]{\mathcal{#1}}
\newcommand{\cA}{\ec{A}}
\newcommand{\cC}{\ec{C}}
\newcommand{\cD}{\ec{D}}
\newcommand{\cK}{\ec{K}}
\newcommand{\cL}{\ec{L}}
\newcommand{\cV}{\ec{V}}
\newcommand{\cW}{\ec{W}}
\newcommand{\rQuiv}{\ec{rQuiv}}
\newcommand{\Cat}{\ec{Cat}}
\newcommand{\Kan}{\ec{Kan}}
\newcommand{\qCat}{\ec{QCat}}
\newcommand{\Set}{\ec{Set}}
\newcommand{\sSet}{\ec{sSet}}
\newcommand{\twoCat}{2\text{-}\Cat}
\newcommand{\sCat}{\sSet\text{-}\Cat}
\newcommand{\eCat}[1]{{#1}\text{-}\Cat}
\newcommand{\qop}[1]{\mathsf{#1}}
\newcommand{\Fun}{\qop{Fun}}
\newcommand{\ho}{\qop{h}}
\newcommand{\hFun}{\qop{hFun}}
\newcommand{\core}{\qop{core}}
\newcommand{\coreop}[1]{{#1}^{\simeq}}
\newcommand{\name}[1]{\ulcorner{#1}\urcorner}
\newcommand{\face}{\delta}
\newcommand{\degen}{\sigma}
\newcommand{\fbv}[1]{\{#1\}}
\newcommand{\op}{^{\mathrm{op}}}
\newcommand{\co}{^{\mathrm{co}}}
\newcommand{\coop}{^{\mathrm{coop}}}
\newcommand{\cosk}{\mathrm{cosk}}
\newcommand{\cod}{\mathrm{cod}}
\newcommand{\dom}{\mathrm{dom}}
\newcommand{\ev}{\mathrm{ev}}
\newcommand{\id}{\mathrm{id}}
\newcommand{\sk}{\mathrm{sk}}
\newcommand{\h}{\mathfrak{h}}
\newcommand{\leib}[1]{\mathbin{\widehat{#1}}}
\newcommand{\uleib}[1]{\widehat{#1}}
\newcommand{\pwr}{\mathbin{\div}}
\newcommand{\coloneq}{:=}
\newcommand{\Del}{\Delta}
\newcommand{\fib}{\twoheadrightarrow}
\newcommand{\we}{\rightsquigarrow}
\newcommand{\trvfib}{\twoheadrightarrow}
\newcommand{\To}{\Rightarrow}
\newcommand{\isoto}{\rightsquigarrow}
\newcommand{\inc}{\hookrightarrow}
\newcommand{\catfour}{[3]}
\newcommand{\catthree}{[2]}
\newcommand{\cattwo}{[1]}
\newcommand{\catone}{[0]}
\newcommand{\catn}{[n-1]}
\newcommand{\catnone}{[n]}
\newcommand{\catntwo}{[n+1]}
\newcommand{\iso}{I}
"#
