import Architect
import InfinityCosmos.ForMathlib.AlgebraicTopology.Quasicategory.TwoTruncated
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplexCategory
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialCategory.Basic
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialCategory.Cotensors
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.Basic
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.CoherentIso
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.Homotopy
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.Horn
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.Monoidal
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.MorphismProperty
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.StdSimplex
import InfinityCosmos.ForMathlib.CategoryTheory.Enriched.Cotensors
import InfinityCosmos.ForMathlib.CategoryTheory.Enriched.Limits.HasConicalLimits
import InfinityCosmos.ForMathlib.CategoryTheory.Enriched.Limits.HasConicalTerminal
import InfinityCosmos.ForMathlib.CategoryTheory.Enriched.Limits.IsConicalLimit
import InfinityCosmos.ForMathlib.CategoryTheory.Enriched.Limits.IsConicalTerminal
import InfinityCosmos.ForMathlib.CategoryTheory.Enriched.MonoidalProdCat
import InfinityCosmos.ForMathlib.InfinityCosmos.Basic
import InfinityCosmos.ForMathlib.InfinityCosmos.Goals
import InfinityCosmos.ForMathlib.InfinityCosmos.Isofibrations
import InfinityCosmos.Init

attribute [blueprint
  "defn:simplex-category"
  (title := "the simplex category")
  (statement := /--
  Let $\Del$ denote the \textbf{simplex category} of finite nonempty ordinals $[n] = \{0 <1 <\cdots
  < n\}$ and order-preserving maps.
  -/)]
  SimplexCategory.smallCategory

attribute [blueprint
  "defn:face-map"
  (title := "elementary face maps")
  (statement := /--
  The \textbf{elementary~face~operators} are the maps
  \begin{center}
  \begin{tikzcd}[row sep=tiny, column sep=small]
     {[n-1]} \arrow[r, tail, "{\face^i}"] & {[n]}  & {0 \leq i \leq n}
  \end{tikzcd}
  \end{center}
  whose images omit the element $i \in [n]$.
  -/)]
  SimplexCategory.δ

attribute [blueprint
  "defn:degeneracy-map"
  (title := "elementary degeneracy maps")
  (statement := /--
    The \textbf{elementary~degeneracy~operators} are the maps
  \begin{center}
  \begin{tikzcd}[row sep=tiny, column sep=small]
   {[n+1]} \arrow[r, two heads, "{\degen^i}"] & {[n]} & {0 \leq i \leq n }
  \end{tikzcd}
  \end{center}
  whose images  double up on the element $i \in [n]$.
  -/)]
  SimplexCategory.σ

attribute [blueprint
  "prop:simplex-cat-factorization"
  (statement := /--
  Every morphism in $\Del$ factors uniquely as an epimorphism followed by a monomorphism; these
  epimorphisms, the \textbf{degeneracy operators}, decompose as composites of elementary degeneracy
  operators, while the monomorphisms, the \textbf{face operators}, decompose as composites of
  elementary face operators.
  -/)
  (proof := /--
  The image factorizations have been formalized but the canonical decompositions into elementary
  face and degeneracy operators remain to be done.
  -/)
  (latexEnv := "proposition")]
  SimplexCategory.instHasStrongEpiImages

attribute [blueprint
  "defn:standard-simplex"
  (title := "standard simplex")
  (statement := /--
  We write $\Delta[n]$ for the \textbf{standard $n$-simplex} the simplicial set represented by $[n]
  \in \Del$.
  -/)]
  SSet.stdSimplex

attribute [blueprint
  "defn:simplex-boundary"
  (title := "simplex boundary")
  (statement := /--
  We write $\partial\Delta[n] \subset \Delta[n]$ for the \textbf{boundary sphere} of the
  $n$-simplex. The sphere $\partial\Delta[n]$ is the simplicial subset generated by the
  codimension-one faces of the $n$-simplex.
  -/)]
  SSet.boundary

attribute [blueprint
  "defn:simplicial-horn"
  (title := "simplicial horn")
  (statement := /--
  We write $\Lambda^k[n] \subset \Delta[n]$ for the $k$-\textbf{horn} in the $n$-simplex. The horn
  $\Lambda^k[n]$ is the further simplicial subset of $\partial\Delta[n]$ that omits the face
  opposite the vertex $k$, but it is defined as a subset of $\Delta[n]$.
  -/)]
  SSet.horn

attribute [blueprint
  "lem:simplex-yoneda"
  (statement := /--
    Each $n$-simplex $x \in X_n$ corresponds to a map of simplicial sets $x \colon \Delta[n] \to X$.
    Accordingly, we write $x \cdot \face^i$ for the $i$th face of the $n$-simplex, an
    $(n-1)$-simplex classified by the composite map
  \begin{center}
  \begin{tikzcd}
  \Delta[n-1] \arrow[r, "\face^i"] & \Delta[n] \arrow[r, "x"] & X.
  \end{tikzcd}
  \end{center}
  -/)
  (proof := /-- This is a special case of the Yoneda lemma. -/)
  (latexEnv := "lemma")]
  SSet.yonedaEquiv

attribute [blueprint
  "defn:sset-category"
  (title := "the category of simplicial sets")
  (statement := /--
  The category of \textbf{simplicial sets} is the category $\sSet \coloneq \Set^{\Del\op}$ of
  pre\-sheaves on the simplex category.
  -/)]
  SSet.largeCategory

attribute [blueprint
  "cor:sset-cat-limits"
  (statement := /-- The category of simplicial sets is complete. -/)
  (proof := /-- Presheaf categories are complete. -/)
  (latexEnv := "corollary")]
  SSet.hasLimits

attribute [blueprint
  "cor:sset-cat-colimits"
  (statement := /-- The category of simplicial sets is cocomplete. -/)
  (proof := /-- Presheaf categories are cocomplete. -/)
  (latexEnv := "corollary")]
  SSet.hasColimits

attribute [blueprint
  "defn:kan-complex"
  (title := "Kan complex")
  (statement := /--
  A \textbf{Kan complex} is a simplicial set admitting extensions as in \eqref{eq:qcat-defn} along
  all horn inclusions $n \geq 1, 0 \leq k \leq n$.
  -/)]
  SSet.KanComplex

attribute [blueprint
  "defn:quasi-category"
  (title := "quasi-category")
  (statement := /--
     A \textbf{quasi-category} is a simplicial set $A$ in which any \textbf{inner horn} can be
     extended to a simplex, solving the displayed lifting problem:
    \begin{figure}\label{eq:qcat-defn}
    \begin{tikzcd}
    \Lambda^k[n] \arrow[r] \arrow[d, hook] & A  \\ \Delta[n] \arrow[ur, dashed]
    \end{tikzcd} \qquad  \text{for}\ \ n \geq 2,\ 0 < k < n.
  \end{figure}
  -/)]
  SSet.Quasicategory

attribute [blueprint
  "prop:nerve-2-coskeletal"
  (statement := /--
  The nerve of a category $C$ is \textbf{2-coskeletal} as a simplicial set, meaning that every
  sphere $\partial\Delta[n] \to C$ with $n \geq 3$ is filled uniquely by an $n$-simplex in $C$, or
  equivalently that the nerve is canonically isomorphic to the right Kan extension of its
  restriction to 2-truncated simplicial sets.\footnote{The equivalence between these two
  perspectives is non-obvious and makes use of Reedy category theory (see \cite[\S
  C.4-5]{RiehlVerity:2022eo}), which does not currently exist in Mathlib.}% (see Definition
  % \ref{defn:sk-cosk}).
  -/)
  (proof := /--
  Note a sphere $\partial\Delta[2] \to C$ extends to a 2-simplex if and only if that arrow along its
  diagonal edge is the composite of the arrows along the edges in the inner horn $\Lambda^1[2]
  \subset \partial\Delta[2] \to C$. The simplices in dimension 3 and above witness the associativity
  of the composition of the path of composable arrows found along their  \textbf{spine}, the
  1-skeletal simplicial subset formed by the edges connecting adjacent vertices. In fact, as
  suggested by the proof of Proposition \ref{prop:nerve-qcat}, any simplicial set in which inner
  horns admit \emph{unique} fillers is isomorphic to the nerve of a 1-category. This
  characterization of nerves is not yet in Mathlib, however, we have proven the one-way result,
  namely that nerves of categories satisfy the ``strict Segal condition'' and this is used in the
  proof of 2-coskeletality.
  -/)
  (latexEnv := "proposition")]
  CategoryTheory.Nerve.cosk₂Iso

attribute [blueprint
  "prop:nerve-qcat"
  (title := "nerves are quasi-categories")
  (statement := /-- Nerves of categories are quasi-categories. -/)
  (proof := /--
   Via the isomorphism $C \cong \cosk_2C$ from Proposition \ref{prop:nerve-2-coskeletal} and the
   associated adjunction $\sk_2 \dashv \cosk_2$ of,   %\ref{defn:sk-cosk},
    the required lifting problem displayed below-left transposes to the one displayed below-right:
   \begin{center}
   \begin{tikzcd}
   \Lambda^k[n] \arrow[d, hook] \arrow[r] & C \cong \cosk_2C & \arrow[d, phantom,
   "\leftrightsquigarrow"] & \sk_2\Lambda^k[n] \arrow[r] \arrow[d, hook] & C \\ \Delta[n] \arrow[ur,
   dashed] & & ~ & \sk_2\Delta[n] \arrow[ur, dashed]
   \end{tikzcd}
   \end{center}
   The functor $\sk_2$ replaces a simplicial set by its \textbf{2-skeleton}, the simplicial subset
   generated by the simplices of dimension at most two. For $n \geq 4$, the inclusion
   $\sk_2\Lambda^k[n]\inc\sk_2\Delta[n]$ is an isomorphism, in which case the lifting problems on
   the right admit (unique) solutions. So it remains only to solve the lifting problems on the left
   in the cases $n=2$ and $n=3$.

  To that end consider
   \begin{center}
   \begin{tikzcd}
   \Lambda^1[2] \arrow[r] \arrow[d, hook] & C & \Lambda^1[3] \arrow[d, hook] \arrow[r]  & C &
   \Lambda^2[3] \arrow[r] \arrow[d, hook] & C \\ \Delta[2] \arrow[ur, dashed] & & \Delta[3]
   \arrow[ur, dashed] & & \Delta[3] \arrow[ur, dashed]
   \end{tikzcd}
   \end{center}
   An inner horn $\Lambda^1[2] \to C$ defines a composable pair of arrows in $C$; an extension to a
   2-simplex exists precisely because any composable pair of arrows admits a (unique) composite.

   An inner horn $\Lambda^1[3] \to C$ specifies the data of three composable arrows in $C$, as
   displayed in the following diagram, together with the composites $gf$, $hg$, and $(hg)f$.
   \begin{center}
   \begin{tikzcd}
   & c_1\arrow[dr, "hg"] \\ c_0 \arrow[ur, "f"] \arrow[dr, "gf"'] \arrow[rr, "(hg)f" near end] & &
   c_3 \\ & c_2 \arrow[ur, "h"']  \arrow[from=uu, crossing over, "g"' near end]
   \end{tikzcd}
   \end{center}
   Because composition is associative, the arrow $(hg)f$ is also the composite of $gf$ followed by
   $h$, which proves that the 2-simplex opposite the vertex $c_1$ is present in $C$; by
   2-coskeletality, the 3-simplex filling this boundary sphere is also present in $C$. The filler
   for a horn $\Lambda^2[3] \to C$ is constructed similarly.
  -/)
  (latexEnv := "proposition")]
  CategoryTheory.Nerve.quasicategory

attribute [blueprint
  "defn:nerve"
  (title := "nerve")
  (statement := /--
  The category $\Cat$ of 1-categories embeds fully faithfully into the category of simplicial sets
  via the \textbf{nerve} functor. An $n$-simplex in the nerve of a 1-category $C$ is a sequence of
  $n$ composable arrows in $C$, or equally a functor $\catnone \to C$ from the ordinal category
  $\catnone$ with objects $0,\ldots, n$ and a unique arrow $i \to j$ just when $i \leq j$.
  -/)]
  CategoryTheory.nerve

attribute [blueprint
  "defn:nerve-functor"
  (title := "nerve functor")
  (statement := /--
  The map $[n] \mapsto \catnone$ defines a fully faithful embedding $\Del\inc\Cat$. From this point
  of view, the nerve functor can be described as a ``restricted Yoneda embedding'' which carries a
  category $C$ to the restriction of the representable functor $\hom(-,C)$ to the image of this
  inclusion.
  -/)]
  CategoryTheory.nerveFunctor

attribute [blueprint
  "defn:one-truncation"
  (statement := /--
  By 1-truncating, any simplicial set $X$ has an underlying \textbf{reflexive quiver} or
  \textbf{reflexive directed graph} with the 0-simplices of $X$ defining the objects and the
  1-simplices defining the arrows:
  \begin{center}
  \begin{tikzcd}
  X_1 \arrow[r, shift left=.75em, "\cdot\face^1"] \arrow[r, shift right=.75em, "\cdot\face^0"'] &
  X_0, \arrow[l, "\cdot\degen^0" description]
  \end{tikzcd}
  \end{center}
  By convention, the source of an arrow $f \in X_1$ is its 0th face $f \cdot \face^1$ (the face
  opposite 1) while the target is its 1st face $f \cdot \face^0$ (the face opposite 0).
  -/)]
  SSet.oneTruncation₂

attribute [blueprint
  "prop:free-refl-quiver"
  (statement := /--
  The functor that carries a category to its underlying reflexive quiver has a left adjoint,
  defining the free category on a reflexive quiver:
  \begin{center}
    \begin{tikzcd}[column sep=huge]
      \mathcal{C}at \arrow[r, start anchor=353, end anchor=190, bend right, hook', "U"'] \arrow[r,
      phantom, "\bot"] & r\mathcal{Q}uiv \arrow[l, start anchor=170, end anchor=7, bend right, "F"'
      pos=.48]
    \end{tikzcd}
    \end{center}
  -/)
  (proof := /-- This has been formalized and is now in Mathlib. -/)
  (latexEnv := "proposition")]
  CategoryTheory.ReflQuiv.adj

attribute [blueprint
  "defn:homotopy-cat"
  (title := /-- {the homotopy category \cite[\S2.4]{GabrielZisman:1967cf}} -/)
  (statement := /--
  The \textbf{free category} on this reflexive directed graph has $X_0$ as its object set,
  degenerate 1-simplices serving as identity morphisms, and nonidentity morphisms defined to be
  finite directed paths of nondegenerate 1-simplices. The \textbf{homotopy category} $\ho{X}$ of $X$
  is the quotient of the free category on its underlying reflexive directed graph by the
  congruence\footnote{A binary relation $\sim$ on parallel arrows of a 1-category is a
  \textbf{congruence} if it is an equivalence relation that is closed under pre- and
  post-composition: if $f \sim g$ then $hfk \sim hgk$.} generated by imposing a composition relation
  $h = g \circ f$ witnessed by 2-simplices
    \begin{center}
    \begin{tikzcd}[row sep=small, column sep=small]
    & x_1 \arrow[dr, "g"] \\ x_0 \arrow[ur, "f"] \arrow[rr, "h"'] & & x_2
    \end{tikzcd}
    \end{center}
  -/)]
  SSet.Truncated.HomotopyCategory

attribute [blueprint
  "prop:ho-nerve-adjunction"
  (statement := /--
   The nerve embedding admits a left adjoint, namely the functor which sends a simplicial set to its
   homotopy category:
  \begin{center}
  \begin{tikzcd}[column sep=huge]
    \mathcal{C}at \arrow[r, start anchor=353, end anchor=190, bend right, hook'] \arrow[r, phantom,
    "\bot"] & s\mathcal{S}et \arrow[l, start anchor=170, end anchor=7, bend right, "\ho"' pos=.48]
  \end{tikzcd}
  \end{center}
  -/)
  (proof := /--
  For any simplicial set $X$, there is a natural map from $X$ to the nerve of its homotopy category
  $\ho{X}$; since nerves are 2-coskeletal, it suffices to define the map $\sk_2X \to \ho{X}$, and
  this is given immediately by the construction of Definition \ref{defn:homotopy-cat}. Note that the
  quotient map $X \to \ho{X}$ becomes an isomorphism upon applying the homotopy category functor and
  is already an isomorphism whenever $X$ is the nerve of a category. Thus the adjointness follows
  %from Lemma \ref{lem:RARI-construction} or
  by direct verification of the triangle equalities.
  -/)
  (latexEnv := "proposition")]
  CategoryTheory.nerveAdjunction

attribute [blueprint
  "prop:nerve-fully-faithful"
  (statement := /-- The nerve functor is fully faithful. -/)
  (proof := /-- This has been formalized and is now in Mathlib. -/)
  (latexEnv := "proposition")]
  CategoryTheory.nerveFunctor.fullyfaithful

attribute [blueprint
  "prop:nerve-reflective"
  (statement := /--
  The homotopy category of the nerve of a 1-category is isomorphic to the original category, as the
  2-simplices in the nerve witness all of the composition relations satisfied by the arrows in the
  underlying reflexive directed graph.
  -/)
  (proof := /-- This has been formalized and is now in Mathlib. -/)
  (latexEnv := "proposition")]
  CategoryTheory.nerveFunctorCompHoFunctorIso

attribute [blueprint
  "lem:ho-preserves-finite-products"
  (statement := /-- The functor $\ho \colon \sSet \to \Cat$ preserves finite products. -/)
  (proof := /--
  Preservation of the terminal object is by direct calculation. By Proposition
  \ref{prop:nerve-reflective}, preservation of binary products is equivalent to the statement that
  the canonical map $N(\cD^\cC) \to N(\cD)^{N\cC}$ involving nerves of categories is an isomorphism.
  On $n$-simplices, this is defined by uncurrying, which is bijection since $\Cat$ is cartesian
  closed.
  -/)
  (latexEnv := "lemma")]
  CategoryTheory.hoFunctor.preservesFiniteProducts

attribute [blueprint
  "defn:simplicial-category"
  (title := "simplicial categories as enriched categories")
  (statement := /--
  The data of a \textbf{simplicial category} is a \textbf{simplicially enriched category} with a set
  of objects and a simplicial set $\cA(x,y)$ of morphisms between each ordered pair of objects. Each
  endo-hom space contains a distinguished 0-simplex $\id_x \in \cA(x,y)_0$, and composition is
  required to define a simplicial map
    \begin{center}
    \begin{tikzcd}
    \cA(y,z) \times \cA(x,y) \arrow[r, "\circ"] & \cA(x,z)
    \end{tikzcd}
    \end{center} The composition is required to be associative and unital, in a sense expressed by
    the commutative diagrams of simplicial sets
    \begin{center}
    \begin{tikzcd}[column sep=small]
    \cA(y,z) \times \cA(x,y) \times \cA(w,x) \arrow[d, "\id \times \circ"'] \arrow[r, "\circ \times
    \id"] & \cA(x,z) \times \cA(w,x) \arrow[d, "\circ"]  \\ \cA(y,z) \times \cA(w,y) \arrow[r,
    "\circ"'] & \cA(w,z)
    \end{tikzcd}
    \begin{tikzcd} \cA(x,y) \arrow[r, "\id_y \times \id"] \arrow[dr, "\id"] \arrow[d, "\id \times
    \id_x"']  & \cA(y,y) \times \cA(x,y) \arrow[d, "\circ"] \\ \cA(x,y) \times \cA(x,x) \arrow[r,
    "\circ"'] & \cA(x,y)
    \end{tikzcd}
    \end{center}
  -/)]
  CategoryTheory.SimplicialCategory

attribute [blueprint
  "defn:underlying-cat"
  (statement := /--
  The category $\cA_0$ of 0-arrows is the \textbf{underlying category} of the simplicial category
  $\cA$, which forgets the higher dimensional simplicial structure.
  -/)]
  CategoryTheory.categoryForgetEnrichment

attribute [blueprint
  "defn:lax-monoidal-functor"
  (statement := /--
   A \textbf{(lax) monoidal functor} between cartesian closed categories $\cV$ and $\cW$ is a
   functor $T \colon \cV \to \cW$ equipped with natural transformations
  \begin{center}
  \begin{tikzcd} \cV \times \cV \arrow[r, "T\times T"] \arrow[dr, phantom,
  "\scriptstyle\Downarrow\phi"] \arrow[d, "\times"'] & \cW \times \cW \arrow[d, "\times"] & \catone
  \arrow[r, "1"] \arrow[dr, "1"'] & \cV \arrow[d, "T"] \\ \cV \arrow[r, "T"'] & \cW  &\arrow[ur,
  phantom, "\scriptstyle\Uparrow\phi_0" pos=.85] & \cW
  \end{tikzcd}
  \end{center}
  so that the evident associativity and unit diagrams commute.
  -/)]
  CategoryTheory.LaxMonoidalFunctor

attribute [blueprint
  "prop:change-of-base"
  (statement := /--
  A finite-product-preserving functor $T \colon \cV \to \cW$ between cartesian closed categories
  induces a change-of-base 2-functor \begin{center} \begin{tikzcd} {\cV}\text{-}\mathcal{C}at
  \arrow[r, "T_*"] & {\cW}\text{-}\mathcal{C}at\, . \end{tikzcd}\end{center}
  -/)
  (proof := /--
      Let $\cC$ be a $\cV$-category and define a $\cW$-category $T_*\cC$ to have the same objects
      and to have mapping objects $T_*\cC(x,y) \coloneq T\cC(x,y)$. The composition and identity
      maps are given by the composites
  \begin{center}
  \begin{tikzcd}[column sep=small] T\cC(y,z)\times T\cC(x,y) \arrow[r, "\cong"] & T(\cC(y,z) \times
  \cC(x,y)) \arrow[r, "T\circ"] & T\cC(x,z) & 1 \arrow[r, "\cong"] & T1 \arrow[r, "T\id_x"] &
  T\cC(x,x)
  \end{tikzcd}
  \end{center}
  which make use of the inverses of the natural maps that arise when a finite-product-preserving
  functor is applied to a finite product. A straightforward diagram chase verifies that $T_*\cC$ is
  a $\cW$-category.

  If $F \colon \cC \to \cD$ is a $\cV$-functor, then we define a $\cW$-functor $T_*F \colon T_*\cC
  \to T_*\cD$ to act on objects by $c \in\cC \mapsto Fc \in \cD$ and with internal action on arrows
  defined by
  \begin{center} \begin{tikzcd} T\cC(x,y) \arrow[r, "TF_{x,y}"] & T\cD(Fx,Fy) \end{tikzcd}
  \end{center}
  Again, a straightforward diagram chase verifies that $T_*F$ is $\cW$-functorial. It is evident
  from this definition that $T_*(GF) = T_*G \cdot T_*F$.

  Finally, let $\alpha \colon F \To G$ be a $\cV$-natural transformation between $\cV$-functors $F,G
  \colon \cC\to \cD$ and define a $\cW$-natural transformation $T_*\alpha \colon T_* F \To T_*G$ to
  have components
  \begin{center}
  \begin{tikzcd} 1 \arrow[r, "\cong"] & T1 \arrow[r, "T\alpha_c"] & T\cD(Fc, Gc)\end{tikzcd}
  \end{center}
  Another straightforward diagram chase verifies that $T_*\alpha$ is $\cW$-natural.

  It remains to verify this assignment is functorial for both horizontal and vertical composition of
  enriched natural transformations. %Consulting Definition \ref{defn:V-cat-2-cat}, we see that
  The component of $T_*(\beta\cdot\alpha)$ is defined by the top-horizontal composite below while
  the component of the vertical composite of $T_*\alpha$ with $T_*\beta \colon T_*G \To T_*H$ is
  defined by the bottom composite: \begin{center}
  \begin{tikzcd} 1 \arrow[r, "\cong"] \arrow[dr, "\cong"'] & T1 \arrow[r, "T(\beta_c\times
  \alpha_c)"] & T(\cD(Gc, Hc) \times \cD(Fc, Gc)) \arrow[r, "T\circ"] & T\cD(Fc,Hc) \\ & T1 \times
  T1 \arrow[u, "\cong"'] \arrow[r, "T\beta_c \times T\alpha_c"'] & T\cD(Gc,Hc) \times T\cD(Fc,Gc)
  \arrow[u, "\cong"']  \end{tikzcd}
  \end{center}
  The square commutates by the naturality of the isomorphism $T(u \times v) \cong Tu \times Tv$,
  while the triangle commutes because 1 is terminal, so the inverses of the displayed isomorphisms
  form a commutative triangle. The argument for functoriality of horizontal composites is similar.
  -/)
  (latexEnv := "proposition")]
  CategoryTheory.instEnrichedCategoryTransportEnrichment
