name = "InfinityCosmos"
defaultTargets = ["InfinityCosmos"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "LeanArchitect"
scope = "hanwenzhu"
rev = "v4.31.0-rc1"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "81a5d257c8e410db227a6665ed08f64fea08e997"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "InfinityCosmos"
