name = "InfinityCosmos"
defaultTargets = ["InfinityCosmos"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "LeanArchitect"
scope = "hanwenzhu"
rev = "v4.33.0-rc1"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "3ef2c2e23a8b5a46554fa771969b89287972b616"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "InfinityCosmos"
