name = "InfinityCosmos"
defaultTargets = ["InfinityCosmos"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "LeanArchitect"
scope = "hanwenzhu"
rev = "v4.31.0-rc1"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "a2bff7b898cdaaddae5789dc8e20445d011003ba"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "InfinityCosmos"
