import Architect
import InfinityCosmos.ForMathlib.AlgebraicTopology.SimplicialSet.Nerve
import Mathlib.AlgebraicTopology.Quasicategory.Nerve

/-!
This file contains imports and `@[blueprint]` attributes which are needed for the blueprint,
e.g. imports which contain used statements but are not imported anywhere else yet.

Eventually, this file should be empty again.
-/

open CategoryTheory

attribute [blueprint
  "prop:nerve-qcat"
  (title := "nerves are quasi-categories")
  (statement := /-- Nerves of categories are quasi-categories. -/)
  (proof := /--
   Via the isomorphism $C \cong \cosk_2C$ from Proposition \ref{prop:nerve-2-coskeletal} and the
   associated adjunction $\sk_2 \dashv \cosk_2$ of,   %\ref{defn:sk-cosk},
    the required lifting problem displayed below-left transposes to the one displayed below-right:
   \begin{center}
   \begin{tikzcd}
   \Lambda^k[n] \arrow[d, hook] \arrow[r] & C \cong \cosk_2C & \arrow[d, phantom,
   "\leftrightsquigarrow"] & \sk_2\Lambda^k[n] \arrow[r] \arrow[d, hook] & C \\ \Delta[n] \arrow[ur,
   dashed] & & ~ & \sk_2\Delta[n] \arrow[ur, dashed]
   \end{tikzcd}
   \end{center}
   The functor $\sk_2$ replaces a simplicial set by its \textbf{2-skeleton}, the simplicial subset
   generated by the simplices of dimension at most two. For $n \geq 4$, the inclusion
   $\sk_2\Lambda^k[n]\inc\sk_2\Delta[n]$ is an isomorphism, in which case the lifting problems on
   the right admit (unique) solutions. So it remains only to solve the lifting problems on the left
   in the cases $n=2$ and $n=3$.

  To that end consider
   \begin{center}
   \begin{tikzcd}
   \Lambda^1[2] \arrow[r] \arrow[d, hook] & C & \Lambda^1[3] \arrow[d, hook] \arrow[r]  & C &
   \Lambda^2[3] \arrow[r] \arrow[d, hook] & C \\ \Delta[2] \arrow[ur, dashed] & & \Delta[3]
   \arrow[ur, dashed] & & \Delta[3] \arrow[ur, dashed]
   \end{tikzcd}
   \end{center}
   An inner horn $\Lambda^1[2] \to C$ defines a composable pair of arrows in $C$; an extension to a
   2-simplex exists precisely because any composable pair of arrows admits a (unique) composite.

   An inner horn $\Lambda^1[3] \to C$ specifies the data of three composable arrows in $C$, as
   displayed in the following diagram, together with the composites $gf$, $hg$, and $(hg)f$.
   \begin{center}
   \begin{tikzcd}
   & c_1\arrow[dr, "hg"] \\ c_0 \arrow[ur, "f"] \arrow[dr, "gf"'] \arrow[rr, "(hg)f" near end] & &
   c_3 \\ & c_2 \arrow[ur, "h"']  \arrow[from=uu, crossing over, "g"' near end]
   \end{tikzcd}
   \end{center}
   Because composition is associative, the arrow $(hg)f$ is also the composite of $gf$ followed by
   $h$, which proves that the 2-simplex opposite the vertex $c_1$ is present in $C$; by
   2-coskeletality, the 3-simplex filling this boundary sphere is also present in $C$. The filler
   for a horn $\Lambda^2[3] \to C$ is constructed similarly.
  -/)
  (latexEnv := "proposition")]
  Nerve.quasicategory
